import Titulo from "../../components/blog/Titulo"
export default function lagoaDosPatosMG() {
    return (
        <>
           
                {/* <Titulo titulo= "Olá Mundo"/> */}

                <h2>Lagoa dos Patos - MG</h2>

                <p> Lagoa dos Patos é um município brasileiro do estado de Minas Gerais. Sua população estimada em 2007 era de 4.448 habitantes. Lagoa dos Patos está localizada a cerca de 20 quilômetros a leste do rio São Francisco e a 106 quilômetros do maior município da região, Montes Claros. São municípios limítrofes com Lagoa dos Patos: Várzea da Palma, Jequitaí, Buritizeiro, São João da Lagoa, Ibiaí e Coração de Jesus. Integra a microrregião de Pirapora. </p>

                <p> Lagoa dos Patos é um município brasileiro do estado de Minas Gerais. Sua população estimada em 2007 era de 4.448 habitantes. Lagoa dos Patos está localizada a cerca de 20 quilômetros a leste do rio São Francisco e a 106 quilômetros do maior município da região, Montes Claros. São municípios limítrofes com Lagoa dos Patos: Várzea da Palma, Jequitaí, Buritizeiro, São João da Lagoa, Ibiaí e Coração de Jesus. Integra a microrregião de Pirapora. </p> <h2>História</h2> <p> O município de Lagoa dos Patos surgiu entorno de 1910, as margens de uma estrada por onde passavam tropeiros de Coração de Jesus para Pirapora, com a chegada do forasteiro conhecido como Aniceto Pedreiro. Este senhor que não revela sua profissão com o nome, apesar de pedreiro como chamado, ele era folião de reis, em sua companhia haviam muitas mulheres e poucos homens, eles iam de fazenda em fazenda, tocavam e cantavam Folia do Bom Jesus[8]. </p> <p> Aniceto Pedreiro não permaneceu aqui por muitos anos, mas foi o suficiente para dar inicio a historia da cidade. Como forasteiro, não tinha lugar fixo, Aniceto afincou neste território o marco construindo seu rancho as margens do córrego boqueirão, para sua sobrevivência plantou mandioca, milho, feijão, cana de açúcar e fumo. chamou aqui de Estrela do Bom Jesus. O senhor Aniceto Pedreiro vendia além de mantimentos, pinga e fumo roleiro, que era produção dele, como não haviam outras vendas o pessoal das fazendas frequentavam a sua venda para dançar, beber e fumar. </p> 
                <h2>Pita e Bebe</h2> 
                <p> Muitos agregados tomaram gosto e construíram seus ranchos ali, daí foi se criando o povoado que devido ao costume do povo, foi chamado de Pita e Bebe, posteriormente foi chamado também de 'pitão'. </p> 
                <h2>Igreja católica</h2> 
                <p> A igreja católica iniciada por Aniceto Pedreiro era uma simples capela. Com o tempo os moradores sentiram necessidade de construir uma capela maior, foram os moradores da localidade que planejaram sua arquitetura, a conclusão da obra foi mais ou menos em 1953. Após se formar uma pequena comunidade, com seu crescimento, em 1932, tornou-se distrito de Coração de Jesus e, em 1962, emancipou-se em município. O topônimo surgiu quando em 1903, se construiu uma pequena represa no córrego Boqueirão, provocando a formação de considerável lagoa. Logo depois ela ela passou a ser o habitat de Patos Selvagens. Sem causa conhecida, a lagoa se transformou num pantanal causando o êxodo das aves. Em 1924 a 'revoada dos patos', no desempenho de sua função surgiram o nome de Lagoa dos Patos para o povoado, que foi acatado.</p> 
                <h2>Música homenagem a Lagoa dos Patos MG - Tutu Ramos</h2> 
                <p>Veja a música completa no artista local - TUTU RAMOS - para entrar em contato com Tutu Ramos acesse: </p>
                    <p>Letra</p> 
                <p>Lá pelos anos, de 1932, nascia uma grande paixão</p> 
                <p>Chamada de pita e bebe depois de pitão</p> <p>Seu morador primeiro Aniceto Pedreiro</p> <p>Tinha como padroeiro o senhor Bom Jesus</p> <p>E no meio de mato e fazenda</p> <p>Brotava uma cidade de brilho e de Luz</p> <p>Sua fama começou a espalhar</p> <p>E novos moradores começaram a chegar</p> <p>Aí já era distrito tinha população</p> <p>Dançar, bebida, fumo, fogueira e leilão</p> <p>E trinta anos depois, através de uma lei veio a emancipação</p> <p>Lagoa dos Patos teria, sua própria política e eleição</p> <p>E hoje como podem ver</p> <p>Temos cultura, esporte e lazer</p> <p>Futebol, festa de vaquejada, trilhas de moto e jogos de carta na praça</p> <p>Quadrilha e festa de são sebastião</p> <p>Pastorinhas mantém a tradição</p> <p>Nossa gente gosta de alegria</p> <p>De caso, verso e prosa e uma boa pescaria</p>  <p>E hoje, agora, 50 anos passou</p> <p>A gente comemora, com esse povo vencedor</p> <p>Parabéns, princesa, nossa estrela do Bom Jesus</p> <p>Sua linda história, surpreende e seduz</p>  <p>E hoje, agora, 50 anos passou</p> <p>A gente comemora, com esse povo lutador</p> <p>Parabéns, princesa, nossa estrela do Bom Jesus</p> <p>Sua linda história, surpreende e seduz</p>  <p>Lá pelos anos, de 1932, nascia uma grande paixão</p> <p>Chamada de pita e bebe depois de pitão</p> <p>Seu morador primeiro Aniceto Pedreiro</p> <p>Tinha como padroeiro o senhor Bom Jesus</p> <p>E no meio de mato e fazenda</p> <p>Brotava uma cidade de brilho e de Luz</p> <p>Sua fama começou a espalhar</p> <p>E novos moradores começaram a chegar</p> <p>Aí já era distrito tinha população</p> <p>Dançar, bebida, fumo, fogueira e leilão</p> <p>E trinta anos depois, através de uma lei veio a emancipação</p> <p>Lagoa dos Patos teria, sua própria política e eleição</p> <p>E hoje como podem ver</p> <p>Temos cultura, esporte e lazer</p> <p>Futebol, festa de vaquejada, trilhas de moto e jogos de carta na praça</p> <p>Quadrilha e festa de são sebastião</p> <p>Pastorinhas mantém a tradição</p> <p>Nossa gente gosta de alegria</p> <p>De caso, verso e prosa e uma boa pescaria</p>  <p>E hoje, agora, 50 anos passou</p> <p>A gente comemora, com esse povo vencedor</p> <p>Parabéns, princesa, nossa estrela do Bom Jesus</p> <p>Sua linda história, surpreende e seduz</p>  <p>E hoje, agora, 50 anos passou</p> <p>A gente comemora, com esse povo lutador</p> <p>Parabéns, princesa, nossa estrela do Bom Jesus</p> <p>Sua linda história, surpreende e seduz</p>  <p>Voz: Parabéns Lagoa dos Patos, pelos seus 50 anos, está é uma homenagem da Escola Municipal Aristides Batista.</p> 
          
                <p>Saiba mais da cidade de Lagoa dos Patos MG</p>
        </>
    )
};
